/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список пользователей */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Создание пользователя */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить фото/аватар пользователя */
        post: operations["UsersController_uploadUserPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить пользователя по id */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        /** Удалить пользователя */
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        /** Обновить пользователя */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/api/users/add-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить роль пользователю */
        post: operations["UsersController_userAddRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/remove-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить роль у пользователя */
        delete: operations["UsersController_userRemoveRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/get-all-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список ролей */
        get: operations["RolesController_getAllRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/create-new-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать новую роль */
        post: operations["RolesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация пользователя */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Авторизация пользователя */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновление access_token по refreshToken cookie (rotation) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (удаляет refresh token) */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/confirm-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Подтверждение email */
        get: operations["AuthController_confirmEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь (по access token) */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Повторная отправка письма подтверждения */
        post: operations["AuthController_resendConfirmation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Смена пароля (по access token) */
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/request-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запрос на восстановление пароля (письмо со ссылкой) */
        post: operations["AuthController_requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/confirm-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Подтверждение восстановления пароля (сброс пароля по токену) */
        post: operations["AuthController_confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-confirmation-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проверка возможности повторной отправки подтверждения email */
        post: operations["AuthController_resendConfirmationStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список товаров */
        get: operations["ProductsController_findAll"];
        put?: never;
        /** Создание товара */
        post: operations["ProductsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить фото товара (до 10 шт.) */
        post: operations["ProductsController_uploadProductPhotos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои товары */
        get: operations["ProductsController_findMy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить товар по id */
        get: operations["ProductsController_findOne"];
        put?: never;
        post?: never;
        /** Удалить товар */
        delete: operations["ProductsController_remove"];
        options?: never;
        head?: never;
        /** Обновить товар */
        patch: operations["ProductsController_update"];
        trace?: never;
    };
    "/api/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список услуг */
        get: operations["ServicesController_findAll"];
        put?: never;
        /** Создание услуги */
        post: operations["ServicesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить фото услуги (до 10 шт.) */
        post: operations["ServicesController_uploadServicePhotos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои услуги */
        get: operations["ServicesController_findMy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить услугу по id */
        get: operations["ServicesController_findOne"];
        put?: never;
        post?: never;
        /** Удалить услугу */
        delete: operations["ServicesController_remove"];
        options?: never;
        head?: never;
        /** Обновить услугу */
        patch: operations["ServicesController_update"];
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список вакансий */
        get: operations["JobsController_findAll"];
        put?: never;
        /** Создание вакансии */
        post: operations["JobsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить фото вакансии (до 10 шт.) */
        post: operations["JobsController_uploadJobPhotos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои вакансии */
        get: operations["JobsController_findMy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить вакансию по id */
        get: operations["JobsController_findOne"];
        put?: never;
        post?: never;
        /** Удалить вакансию */
        delete: operations["JobsController_remove"];
        options?: never;
        head?: never;
        /** Обновить вакансию */
        patch: operations["JobsController_update"];
        trace?: never;
    };
    "/api/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список резюме */
        get: operations["ResumesController_findAll"];
        put?: never;
        /** Создание резюме */
        post: operations["ResumesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои резюме */
        get: operations["ResumesController_findMy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить резюме по id */
        get: operations["ResumesController_findOne"];
        put?: never;
        post?: never;
        /** Удалить резюме */
        delete: operations["ResumesController_remove"];
        options?: never;
        head?: never;
        /** Обновить резюме */
        patch: operations["ResumesController_update"];
        trace?: never;
    };
    "/api/support": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SupportController_sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FavoritesController_getFavorites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FavoritesController_addProduct"];
        delete: operations["FavoritesController_removeProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/products/{id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FavoritesController_checkProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FavoritesController_addService"];
        delete: operations["FavoritesController_removeService"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/services/{id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FavoritesController_checkService"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FavoritesController_addJob"];
        delete: operations["FavoritesController_removeJob"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/jobs/{id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FavoritesController_checkJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все локации */
        get: operations["LocationsController_findAll"];
        put?: never;
        /** Добавить локации (только для админа) */
        post: operations["LocationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список стран */
        get: operations["LocationsController_getCountries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/countries/{country}/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список регионов по стране */
        get: operations["LocationsController_getRegionsByCountry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/countries/{country}/regions/{region}/localities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список районов по региону */
        get: operations["LocationsController_getLocalitiesByRegion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить локацию по ID */
        get: operations["LocationsController_findOne"];
        put?: never;
        post?: never;
        /** Удалить локацию (только для админа) */
        delete: operations["LocationsController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subcategories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все подкатегории */
        get: operations["SubcategoriesController_findAll"];
        put?: never;
        /** Добавить подкатегории (только для админа) */
        post: operations["SubcategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subcategories/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить подкатегории для товаров */
        get: operations["SubcategoriesController_getProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subcategories/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить подкатегории для услуг */
        get: operations["SubcategoriesController_getServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subcategories/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить подкатегории для вакансий */
        get: operations["SubcategoriesController_getJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subcategories/custom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить пользовательские подкатегории */
        get: operations["SubcategoriesController_getCustom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserDto: {
            /**
             * @description Почта пользователя
             * @example you@mail.ru
             */
            email: string;
            /**
             * @description Пароль пользователя (в открытом виде)
             * @example qwerty123
             */
            password: string;
            /**
             * @description Имя пользователя
             * @example Иван
             */
            name: string;
            /**
             * @description Признак подтверждения email
             * @example false
             */
            isEmailVerified?: boolean;
            /**
             * @description Страна
             * @example Россия
             */
            country?: string;
            /**
             * @description Регион
             * @example Московская область
             */
            region?: string;
            /**
             * @description Район
             * @example Истринский
             */
            district?: string;
            /**
             * @description Является ли пользователь поселением/поместьем
             * @example false
             */
            isEstate?: boolean;
            /**
             * @description Тип (INDIVIDUAL/SETTLEMENT)
             * @enum {string}
             */
            estateType?: "INDIVIDUAL" | "SETTLEMENT";
            /**
             * @description Название поселения
             * @example Родовое поселение "Солнечное"
             */
            settlement?: string;
            /**
             * @description Родовое поместье
             * @example Родовое поместье "Луговое"
             */
            estate?: string;
            /**
             * @description Фото/аватар (URL)
             * @example https://storage.yandexcloud.net/bucket/users/xxx.jpg
             */
            photoUrl?: string;
            /**
             * @description О себе
             * @example Я занимаюсь пчеловодством уже 10 лет
             */
            about?: string;
            /**
             * @description Телефон для связи
             * @example +79991234567
             */
            phone?: string;
            /**
             * @description Email для связи (отличный от логина)
             * @example contact@example.com
             */
            contactEmail?: string;
        };
        UploadResultDto: {
            /** @example users/uuid.jpg */
            key: string;
            /** @example https://storage.yandexcloud.net/bucket/users/uuid.jpg */
            url: string;
        };
        UpdateUserDto: {
            /**
             * @description Почта пользователя
             * @example you@mail.ru
             */
            email?: string;
            /**
             * @description Пароль пользователя (в открытом виде)
             * @example qwerty123
             */
            password?: string;
            /**
             * @description Имя пользователя
             * @example Иван
             */
            name?: string;
            /**
             * @description Признак подтверждения email
             * @example false
             */
            isEmailVerified?: boolean;
            /**
             * @description Страна
             * @example Россия
             */
            country?: string;
            /**
             * @description Регион
             * @example Московская область
             */
            region?: string;
            /**
             * @description Район
             * @example Истринский
             */
            district?: string;
            /**
             * @description Является ли пользователь поселением/поместьем
             * @example false
             */
            isEstate?: boolean;
            /**
             * @description Тип (INDIVIDUAL/SETTLEMENT)
             * @enum {string}
             */
            estateType?: "INDIVIDUAL" | "SETTLEMENT";
            /**
             * @description Название поселения
             * @example Родовое поселение "Солнечное"
             */
            settlement?: string;
            /**
             * @description Родовое поместье
             * @example Родовое поместье "Луговое"
             */
            estate?: string;
            /**
             * @description Фото/аватар (URL)
             * @example https://storage.yandexcloud.net/bucket/users/xxx.jpg
             */
            photoUrl?: string;
            /**
             * @description О себе
             * @example Я занимаюсь пчеловодством уже 10 лет
             */
            about?: string;
            /**
             * @description Телефон для связи
             * @example +79991234567
             */
            phone?: string;
            /**
             * @description Email для связи (отличный от логина)
             * @example contact@example.com
             */
            contactEmail?: string;
        };
        AddRoleDto: {
            /**
             * @description Название существующей роли
             * @example admin
             */
            value: string;
            /**
             * @description Идентификатор пользователя
             * @example 1
             */
            userId: number;
        };
        CreateRoleDto: {
            /**
             * @description Название существующей роли
             * @example admin
             */
            value: string;
        };
        RegisterDto: {
            /**
             * @description Почта пользователя
             * @example you@mail.ru
             */
            email: string;
            /**
             * @description Пароль пользователя
             * @example qwerty123
             */
            password: string;
            /**
             * @description Имя пользователя
             * @example Иван
             */
            name: string;
        };
        LoginDto: {
            /**
             * @description Почта пользователя
             * @example you@mail.ru
             */
            email: string;
            /**
             * @description Пароль пользователя
             * @example qwerty123
             */
            password: string;
        };
        ResendConfirmationDto: {
            email: string;
        };
        ResendConfirmationResponseDto: {
            /**
             * @example sent
             * @enum {string}
             */
            status: "ok" | "sent" | "cooldown";
            /**
             * @description Оставшееся время ожидания в секундах (только для cooldown)
             * @example 42
             */
            secondsLeft?: number;
        };
        ChangePasswordDto: {
            currentPassword: string;
            newPassword: string;
        };
        RequestPasswordResetDto: {
            email: string;
        };
        ConfirmPasswordResetDto: {
            token: string;
            newPassword: string;
        };
        ResendConfirmationStatusDto: {
            email: string;
        };
        CreateProductDto: {
            /**
             * @description Название товара
             * @example Мёд липовый
             */
            title: string;
            /**
             * @description Описание
             * @example Натуральный мёд с пасеки
             */
            description?: string;
            /**
             * @description Цена
             * @example 500
             */
            price: number;
            /**
             * @description Валюта (RUB, BYN, UAH, KZT)
             * @default RUB
             * @example RUB
             * @enum {string}
             */
            currency: "RUB" | "BYN" | "UAH" | "KZT";
            /**
             * @description Категория
             * @example Еда
             */
            category?: string;
            /**
             * @description Ссылки на фото товара (до 10 шт.)
             * @example [
             *       "https://storage.yandexcloud.net/bucket/products/xxx.jpg"
             *     ]
             */
            photoUrls?: string[];
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId: number;
        };
        UpdateProductDto: {
            /**
             * @description Название товара
             * @example Мёд липовый
             */
            title?: string;
            /**
             * @description Описание
             * @example Натуральный мёд с пасеки
             */
            description?: string;
            /**
             * @description Цена
             * @example 500
             */
            price?: number;
            /**
             * @description Валюта (RUB, BYN, UAH, KZT)
             * @default RUB
             * @example RUB
             * @enum {string}
             */
            currency: "RUB" | "BYN" | "UAH" | "KZT";
            /**
             * @description Категория
             * @example Еда
             */
            category?: string;
            /**
             * @description Ссылки на фото товара (до 10 шт.)
             * @example [
             *       "https://storage.yandexcloud.net/bucket/products/xxx.jpg"
             *     ]
             */
            photoUrls?: string[];
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId?: number;
        };
        CreateServiceDto: {
            /**
             * @description Название услуги
             * @example Стрижка
             */
            title: string;
            /**
             * @description Описание
             * @example Мужская/женская стрижка
             */
            description?: string;
            /**
             * @description Цена (если применимо)
             * @example 1200
             */
            price?: number;
            /**
             * @description Валюта (RUB, BYN, UAH, KZT)
             * @default RUB
             * @example RUB
             * @enum {string}
             */
            currency: "RUB" | "BYN" | "UAH" | "KZT";
            /**
             * @description Категория
             * @example Красота
             */
            category?: string;
            /**
             * @description Ссылки на фото услуги (до 10 шт.)
             * @example [
             *       "https://storage.yandexcloud.net/bucket/services/xxx.jpg"
             *     ]
             */
            photoUrls?: string[];
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId: number;
        };
        UpdateServiceDto: {
            /**
             * @description Название услуги
             * @example Стрижка
             */
            title?: string;
            /**
             * @description Описание
             * @example Мужская/женская стрижка
             */
            description?: string;
            /**
             * @description Цена (если применимо)
             * @example 1200
             */
            price?: number;
            /**
             * @description Валюта (RUB, BYN, UAH, KZT)
             * @default RUB
             * @example RUB
             * @enum {string}
             */
            currency: "RUB" | "BYN" | "UAH" | "KZT";
            /**
             * @description Категория
             * @example Красота
             */
            category?: string;
            /**
             * @description Ссылки на фото услуги (до 10 шт.)
             * @example [
             *       "https://storage.yandexcloud.net/bucket/services/xxx.jpg"
             *     ]
             */
            photoUrls?: string[];
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId?: number;
        };
        CreateJobDto: {
            /**
             * @description Название вакансии
             * @example Плотник
             */
            title: string;
            /**
             * @description Описание
             * @example Нужен плотник на стройку
             */
            description?: string;
            /**
             * @description Зарплата (если указана)
             * @example 80000
             */
            salary?: number;
            /**
             * @description Валюта (RUB, BYN, UAH, KZT)
             * @default RUB
             * @example RUB
             * @enum {string}
             */
            currency: "RUB" | "BYN" | "UAH" | "KZT";
            /**
             * @description Категория
             * @example Строительство
             */
            category?: string;
            /**
             * @description Ссылки на фото (до 10 шт.)
             * @example [
             *       "https://storage.yandexcloud.net/bucket/jobs/xxx.jpg"
             *     ]
             */
            photoUrls?: string[];
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId: number;
        };
        UpdateJobDto: {
            /**
             * @description Название вакансии
             * @example Плотник
             */
            title?: string;
            /**
             * @description Описание
             * @example Нужен плотник на стройку
             */
            description?: string;
            /**
             * @description Зарплата (если указана)
             * @example 80000
             */
            salary?: number;
            /**
             * @description Валюта (RUB, BYN, UAH, KZT)
             * @default RUB
             * @example RUB
             * @enum {string}
             */
            currency: "RUB" | "BYN" | "UAH" | "KZT";
            /**
             * @description Категория
             * @example Строительство
             */
            category?: string;
            /**
             * @description Ссылки на фото (до 10 шт.)
             * @example [
             *       "https://storage.yandexcloud.net/bucket/jobs/xxx.jpg"
             *     ]
             */
            photoUrls?: string[];
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId?: number;
        };
        CreateResumeDto: {
            /**
             * @description Название резюме
             * @example Frontend разработчик
             */
            title: string;
            /**
             * @description Описание
             * @example Опыт 3 года, React/TS
             */
            description?: string;
            /**
             * @description Навыки (строкой)
             * @example React, TypeScript, Next.js
             */
            skills?: string;
            /**
             * @description Категория
             * @example IT
             */
            category?: string;
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId: number;
        };
        UpdateResumeDto: {
            /**
             * @description Название резюме
             * @example Frontend разработчик
             */
            title?: string;
            /**
             * @description Описание
             * @example Опыт 3 года, React/TS
             */
            description?: string;
            /**
             * @description Навыки (строкой)
             * @example React, TypeScript, Next.js
             */
            skills?: string;
            /**
             * @description Категория
             * @example IT
             */
            category?: string;
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId?: number;
        };
        SupportMessageDto: {
            /**
             * @description Текст сообщения
             * @example Сообщение
             */
            message: string;
        };
        LocationItemDto: {
            /**
             * @description Страна
             * @example Россия
             */
            country: string;
            /**
             * @description Регион
             * @example Московская область
             */
            region?: string;
            /**
             * @description Район/Населенный пункт
             * @example Истринский
             */
            locality?: string;
        };
        CreateLocationsDto: {
            /**
             * @description Массив локаций для добавления
             * @example [
             *       {
             *         "country": "Россия",
             *         "region": "Московская область",
             *         "locality": "Истринский"
             *       },
             *       {
             *         "country": "Россия",
             *         "region": "Чувашия",
             *         "locality": "Алатырский"
             *       }
             *     ]
             */
            locations: components["schemas"]["LocationItemDto"][];
        };
        SubcategoryItemDto: {
            /**
             * @description Название подкатегории
             * @example Эко-товары
             */
            name: string;
            /**
             * @description Тип категории
             * @example product
             * @enum {string}
             */
            type: "product" | "service" | "job";
            /**
             * @description Пользовательская подкатегория
             * @example false
             */
            isCustom?: boolean;
        };
        CreateSubcategoriesDto: {
            /**
             * @description Массив подкатегорий для добавления
             * @example [
             *       {
             *         "name": "Эко-товары",
             *         "type": "product"
             *       },
             *       {
             *         "name": "Ремесленные изделия",
             *         "type": "product"
             *       },
             *       {
             *         "name": "Консультации",
             *         "type": "service"
             *       }
             *     ]
             */
            subcategories: components["schemas"]["SubcategoryItemDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список пользователей */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description Пользователь создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_uploadUserPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResultDto"];
                };
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пользователь */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пользователь удалён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description Пользователь обновлён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_userAddRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRoleDto"];
            };
        };
        responses: {
            /** @description Операция прошла успешно. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JWT токен не указан в заголовках */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Некоректный JWT токен или роль пользователя */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_userRemoveRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRoleDto"];
            };
        };
        responses: {
            /** @description Операция прошла успешно. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JWT токен не указан в заголовках */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Некоректный JWT токен или роль пользователя */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_getAllRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Операция прошла успешно. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            /** @description Операция прошла успешно. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Успешная регистрация */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Неккоректные данные */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Успешная авторизация */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Неккоректные данные */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_confirmEmail: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resendConfirmation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendConfirmationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResendConfirmationResponseDto"];
                };
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPasswordResetDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPasswordResetDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resendConfirmationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendConfirmationStatusDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список товаров */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            /** @description Товар создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_uploadProductPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResultDto"][];
                };
            };
        };
    };
    ProductsController_findMy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список товаров пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Товар */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Товар не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Товар удалён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            /** @description Товар обновлён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServicesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список услуг */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServicesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceDto"];
            };
        };
        responses: {
            /** @description Услуга создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServicesController_uploadServicePhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResultDto"][];
                };
            };
        };
    };
    ServicesController_findMy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список услуг пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServicesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Услуга */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Услуга не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServicesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Услуга удалена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServicesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServiceDto"];
            };
        };
        responses: {
            /** @description Услуга обновлена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список вакансий */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobDto"];
            };
        };
        responses: {
            /** @description Вакансия создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobsController_uploadJobPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResultDto"][];
                };
            };
        };
    };
    JobsController_findMy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список вакансий пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вакансия */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Вакансия не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вакансия удалена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateJobDto"];
            };
        };
        responses: {
            /** @description Вакансия обновлена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список резюме */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResumeDto"];
            };
        };
        responses: {
            /** @description Резюме создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_findMy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список резюме пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Резюме */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Резюме не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Резюме удалено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResumeDto"];
            };
        };
        responses: {
            /** @description Резюме обновлено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SupportController_sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupportMessageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_getFavorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_addProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_removeProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_checkProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_addService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_removeService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_checkService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_addJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_removeJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_checkJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationsDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationsController_getCountries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationsController_getRegionsByCountry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationsController_getLocalitiesByRegion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country: string;
                region: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubcategoriesController_findAll: {
        parameters: {
            query?: {
                /** @description Фильтр по типу категории */
                type?: "product" | "service" | "job";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubcategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubcategoriesDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubcategoriesController_getProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubcategoriesController_getServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubcategoriesController_getJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubcategoriesController_getCustom: {
        parameters: {
            query: {
                type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
