/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список пользователей */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Создание пользователя */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить фото/аватар пользователя */
        post: operations["UsersController_uploadUserPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить пользователя по id */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        /** Удалить пользователя */
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        /** Обновить пользователя */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/api/users/add-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить роль пользователю */
        post: operations["UsersController_userAddRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/remove-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить роль у пользователя */
        delete: operations["UsersController_userRemoveRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/get-all-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список ролей */
        get: operations["RolesController_getAllRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/create-new-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать новую роль */
        post: operations["RolesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация пользователя */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Авторизация пользователя */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновление access_token по refreshToken cookie (rotation) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (удаляет refresh token) */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/confirm-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Подтверждение email */
        get: operations["AuthController_confirmEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь (по access token) */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Повторная отправка письма подтверждения */
        post: operations["AuthController_resendConfirmation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Смена пароля (по access token) */
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/request-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запрос на восстановление пароля (письмо со ссылкой) */
        post: operations["AuthController_requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/confirm-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Подтверждение восстановления пароля (сброс пароля по токену) */
        post: operations["AuthController_confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список товаров */
        get: operations["ProductsController_findAll"];
        put?: never;
        /** Создание товара */
        post: operations["ProductsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить фото товара (до 10 шт.) */
        post: operations["ProductsController_uploadProductPhotos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить товар по id */
        get: operations["ProductsController_findOne"];
        put?: never;
        post?: never;
        /** Удалить товар */
        delete: operations["ProductsController_remove"];
        options?: never;
        head?: never;
        /** Обновить товар */
        patch: operations["ProductsController_update"];
        trace?: never;
    };
    "/api/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список услуг */
        get: operations["ServicesController_findAll"];
        put?: never;
        /** Создание услуги */
        post: operations["ServicesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить услугу по id */
        get: operations["ServicesController_findOne"];
        put?: never;
        post?: never;
        /** Удалить услугу */
        delete: operations["ServicesController_remove"];
        options?: never;
        head?: never;
        /** Обновить услугу */
        patch: operations["ServicesController_update"];
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список вакансий */
        get: operations["JobsController_findAll"];
        put?: never;
        /** Создание вакансии */
        post: operations["JobsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить вакансию по id */
        get: operations["JobsController_findOne"];
        put?: never;
        post?: never;
        /** Удалить вакансию */
        delete: operations["JobsController_remove"];
        options?: never;
        head?: never;
        /** Обновить вакансию */
        patch: operations["JobsController_update"];
        trace?: never;
    };
    "/api/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список резюме */
        get: operations["ResumesController_findAll"];
        put?: never;
        /** Создание резюме */
        post: operations["ResumesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить резюме по id */
        get: operations["ResumesController_findOne"];
        put?: never;
        post?: never;
        /** Удалить резюме */
        delete: operations["ResumesController_remove"];
        options?: never;
        head?: never;
        /** Обновить резюме */
        patch: operations["ResumesController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserDto: {
            /**
             * @description Почта пользователя
             * @example you@mail.ru
             */
            email: string;
            /**
             * @description Пароль пользователя (в открытом виде)
             * @example qwerty123
             */
            password: string;
            /**
             * @description Имя пользователя
             * @example Иван
             */
            name: string;
            /**
             * @description Признак подтверждения email
             * @example false
             */
            isEmailVerified?: boolean;
            /**
             * @description Страна
             * @example Россия
             */
            country?: string;
            /**
             * @description Регион
             * @example Московская область
             */
            region?: string;
            /**
             * @description Район
             * @example Истринский
             */
            district?: string;
            /**
             * @description Является ли пользователь поселением/поместьем
             * @example false
             */
            isEstate?: boolean;
            /**
             * @description Тип (INDIVIDUAL/SETTLEMENT)
             * @enum {string}
             */
            estateType?: "INDIVIDUAL" | "SETTLEMENT";
            /**
             * @description Название поселения
             * @example Родовое поселение "Солнечное"
             */
            settlement?: string;
            /**
             * @description Фото/аватар (URL)
             * @example https://storage.yandexcloud.net/bucket/users/xxx.jpg
             */
            photoUrl?: string;
        };
        UploadResultDto: {
            /** @example users/uuid.jpg */
            key: string;
            /** @example https://storage.yandexcloud.net/bucket/users/uuid.jpg */
            url: string;
        };
        UpdateUserDto: {
            /**
             * @description Почта пользователя
             * @example you@mail.ru
             */
            email?: string;
            /**
             * @description Пароль пользователя (в открытом виде)
             * @example qwerty123
             */
            password?: string;
            /**
             * @description Имя пользователя
             * @example Иван
             */
            name?: string;
            /**
             * @description Признак подтверждения email
             * @example false
             */
            isEmailVerified?: boolean;
            /**
             * @description Страна
             * @example Россия
             */
            country?: string;
            /**
             * @description Регион
             * @example Московская область
             */
            region?: string;
            /**
             * @description Район
             * @example Истринский
             */
            district?: string;
            /**
             * @description Является ли пользователь поселением/поместьем
             * @example false
             */
            isEstate?: boolean;
            /**
             * @description Тип (INDIVIDUAL/SETTLEMENT)
             * @enum {string}
             */
            estateType?: "INDIVIDUAL" | "SETTLEMENT";
            /**
             * @description Название поселения
             * @example Родовое поселение "Солнечное"
             */
            settlement?: string;
            /**
             * @description Фото/аватар (URL)
             * @example https://storage.yandexcloud.net/bucket/users/xxx.jpg
             */
            photoUrl?: string;
        };
        AddRoleDto: {
            /**
             * @description Название существующей роли
             * @example admin
             */
            value: string;
            /**
             * @description Идентификатор пользователя
             * @example 1
             */
            userId: number;
        };
        CreateRoleDto: {
            /**
             * @description Название существующей роли
             * @example admin
             */
            value: string;
        };
        RegisterDto: {
            /**
             * @description Почта пользователя
             * @example you@mail.ru
             */
            email: string;
            /**
             * @description Пароль пользователя
             * @example qwerty123
             */
            password: string;
            /**
             * @description Имя пользователя
             * @example Иван
             */
            name: string;
        };
        LoginDto: {
            /**
             * @description Почта пользователя
             * @example you@mail.ru
             */
            email: string;
            /**
             * @description Пароль пользователя
             * @example qwerty123
             */
            password: string;
        };
        ResendConfirmationDto: {
            email: string;
        };
        ChangePasswordDto: {
            currentPassword: string;
            newPassword: string;
        };
        RequestPasswordResetDto: {
            email: string;
        };
        ConfirmPasswordResetDto: {
            token: string;
            newPassword: string;
        };
        CreateProductDto: {
            /**
             * @description Название товара
             * @example Мёд липовый
             */
            title: string;
            /**
             * @description Описание
             * @example Натуральный мёд с пасеки
             */
            description?: string;
            /**
             * @description Цена
             * @example 500
             */
            price: number;
            /**
             * @description Категория
             * @example Еда
             */
            category?: string;
            /**
             * @description Ссылки на фото товара (до 10 шт.)
             * @example [
             *       "https://storage.yandexcloud.net/bucket/products/xxx.jpg"
             *     ]
             */
            photoUrls?: string[];
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId: number;
        };
        UpdateProductDto: {
            /**
             * @description Название товара
             * @example Мёд липовый
             */
            title?: string;
            /**
             * @description Описание
             * @example Натуральный мёд с пасеки
             */
            description?: string;
            /**
             * @description Цена
             * @example 500
             */
            price?: number;
            /**
             * @description Категория
             * @example Еда
             */
            category?: string;
            /**
             * @description Ссылки на фото товара (до 10 шт.)
             * @example [
             *       "https://storage.yandexcloud.net/bucket/products/xxx.jpg"
             *     ]
             */
            photoUrls?: string[];
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId?: number;
        };
        CreateServiceDto: {
            /**
             * @description Название услуги
             * @example Стрижка
             */
            title: string;
            /**
             * @description Описание
             * @example Мужская/женская стрижка
             */
            description?: string;
            /**
             * @description Цена (если применимо)
             * @example 1200
             */
            price?: number;
            /**
             * @description Категория
             * @example Красота
             */
            category?: string;
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId: number;
        };
        UpdateServiceDto: {
            /**
             * @description Название услуги
             * @example Стрижка
             */
            title?: string;
            /**
             * @description Описание
             * @example Мужская/женская стрижка
             */
            description?: string;
            /**
             * @description Цена (если применимо)
             * @example 1200
             */
            price?: number;
            /**
             * @description Категория
             * @example Красота
             */
            category?: string;
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId?: number;
        };
        CreateJobDto: {
            /**
             * @description Название вакансии
             * @example Плотник
             */
            title: string;
            /**
             * @description Описание
             * @example Нужен плотник на стройку
             */
            description?: string;
            /**
             * @description Зарплата (если указана)
             * @example 80000
             */
            salary?: number;
            /**
             * @description Категория
             * @example Строительство
             */
            category?: string;
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId: number;
        };
        UpdateJobDto: {
            /**
             * @description Название вакансии
             * @example Плотник
             */
            title?: string;
            /**
             * @description Описание
             * @example Нужен плотник на стройку
             */
            description?: string;
            /**
             * @description Зарплата (если указана)
             * @example 80000
             */
            salary?: number;
            /**
             * @description Категория
             * @example Строительство
             */
            category?: string;
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId?: number;
        };
        CreateResumeDto: {
            /**
             * @description Название резюме
             * @example Frontend разработчик
             */
            title: string;
            /**
             * @description Описание
             * @example Опыт 3 года, React/TS
             */
            description?: string;
            /**
             * @description Навыки (строкой)
             * @example React, TypeScript, Next.js
             */
            skills?: string;
            /**
             * @description Категория
             * @example IT
             */
            category?: string;
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId: number;
        };
        UpdateResumeDto: {
            /**
             * @description Название резюме
             * @example Frontend разработчик
             */
            title?: string;
            /**
             * @description Описание
             * @example Опыт 3 года, React/TS
             */
            description?: string;
            /**
             * @description Навыки (строкой)
             * @example React, TypeScript, Next.js
             */
            skills?: string;
            /**
             * @description Категория
             * @example IT
             */
            category?: string;
            /**
             * @description ID пользователя-владельца
             * @example 1
             */
            userId?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список пользователей */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description Пользователь создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_uploadUserPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResultDto"];
                };
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пользователь */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пользователь удалён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description Пользователь обновлён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_userAddRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRoleDto"];
            };
        };
        responses: {
            /** @description Операция прошла успешно. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JWT токен не указан в заголовках */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Некоректный JWT токен или роль пользователя */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_userRemoveRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRoleDto"];
            };
        };
        responses: {
            /** @description Операция прошла успешно. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JWT токен не указан в заголовках */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Некоректный JWT токен или роль пользователя */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_getAllRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Операция прошла успешно. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            /** @description Операция прошла успешно. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Успешная регистрация */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Неккоректные данные */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Успешная авторизация */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Неккоректные данные */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_confirmEmail: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resendConfirmation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendConfirmationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPasswordResetDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPasswordResetDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список товаров */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            /** @description Товар создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_uploadProductPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResultDto"][];
                };
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Товар */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Товар не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Товар удалён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            /** @description Товар обновлён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServicesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список услуг */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServicesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceDto"];
            };
        };
        responses: {
            /** @description Услуга создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServicesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Услуга */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Услуга не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServicesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Услуга удалена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServicesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServiceDto"];
            };
        };
        responses: {
            /** @description Услуга обновлена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список вакансий */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobDto"];
            };
        };
        responses: {
            /** @description Вакансия создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вакансия */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Вакансия не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вакансия удалена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateJobDto"];
            };
        };
        responses: {
            /** @description Вакансия обновлена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список резюме */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResumeDto"];
            };
        };
        responses: {
            /** @description Резюме создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Резюме */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Резюме не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Резюме удалено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResumeDto"];
            };
        };
        responses: {
            /** @description Резюме обновлено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
